### Create a new task
POST http://localhost:8080/v1/users/{{user}}/tasks
Content-Type: application/json
Accept: application/json

{
  "title": "{{$random.alphabetic(10)}}",
  "description": "{{$random.alphanumeric(100)}}",
  "dueDate": "2024-02-06",
  "priority": "LOW",
  "assignee": "{{assignee}}"
}

> {%
    client.global.set("taskId", response.body.id);
%}

### Update status
PUT http://localhost:8080/v1/tasks/{{taskId}}/status
Content-Type: application/json
Accept: application/json

{
  "status": "DONE"
}


### Get all user tasks
GET http://localhost:8080/v1/users/{{user}}/tasks
Accept: application/json